server:
  port: 8080
  servlet:
    context-path: /food-court/users

spring:
  datasource:
    url: jdbc:mysql://localhost/USUARIOS
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "clave-super-secreta-cambia-en-prod"
  token-validity: 36000000  # 10 horas en milisegundos

springdoc:
  swagger-ui:
    enabled: true
    persistAuthorization: true

appDescription: "User API"
appVersion: "1.0.0"